config/routes.rb
Rails.application.routes.draw do
  root "snippets#index"
  get "snippets/index/:language" => "snippets#indexs", as: :indexs_snippets
  resources :snippets

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  validates :kind, presence: true
  validates :title, presence: true, uniqueness: {scope: :kind}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action :find_snippet, only: [:show, :edit, :update, :destroy]

  def new
    @s = Snippet.new
  end

  def create
    snippet_params = params.require(:snippet).permit([:kind, :title, :work])
    @s = Snippet.new snippet_params
    if @s.save
      redirect_to snippet_path(@s)
    else
      render :new
    end
  end

  def show

  end

  def edit

  end

  def update
    if @s.update snippet_params
      redirect_to(snippet_path(@s))
    else
      render :edit
    end
  end

  def index
    #@snippets = Snippet.all
    @snippet_languages = Array.new
    @snippet_languages[0] = ["Ruby", Snippet.where(kind: "Ruby")]
    @snippet_languages[1] = ["HTML", Snippet.where(kind: "HTML")]
    @snippet_languages[2] = ["CSS", Snippet.where(kind: "CSS")]
    @snippet_languages[3] = ["JavaScript", Snippet.where(kind: "JavaScript")]

  end

  def destroy
    @s.destroy
    flash[:notice] = "Code snippet deleted successfully"
    redirect_to snippets_path
  end

  def indexs
    @language = params[:language]
    @snippets = Snippet.where(kind: @language)
  end

  private

  def snippet_params
    params.require(:snippet).permit([:kind, :title, :work])
  end

  def find_snippet
    @s = Snippet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>" ><i class='glyphicon glyphicon-home'></i> Home</a>
    </div>

<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeSnippets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "/layouts/nav" %>

    <% if flash[:notice]%>
      <div class="alert alert-success"><%= flash[:notice] %></div>
    <% elsif flash[:alert]  %>
      <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/snippets/_form.html.erb
<%= @s.errors.full_messages.join(", ") %>
<%= form_for @s do |f| %>
  <div class="form-group">
    <%#= f.collection_select :score_id, Score.all, :id, :name %>
    <%= f.select :kind, ["Ruby", "HTML", "CSS", "JavaScript"] %>
  </div>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :work %>
    <%= f.text_area :work, class: "form-control" %>
  </div>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/snippets/edit.html.erb
<h1>Editing Code Snippet</h1>

<%= render "form" %>

app/views/snippets/index.html.erb
<h1>All Code Snippets</h1>
<%= link_to("New Snippet", new_snippet_path, class: "btn btn-primary") %>
<div>
  <% @snippet_languages.each do |language_snippets| %>
    <div class="well">
        <%= link_to "#{language_snippets[0]} (#{language_snippets[1].length} Snippets)", indexs_snippets_path(language_snippets[0]) %>
    </div>
  <% end %>
</div>

app/views/snippets/indexs.html.erb
<h1><%= @language %> Code Snippets</h1>

<div>
  <% @snippets.each do |s| %>
    <div class="well">
        <%= link_to s.title, snippet_path(s) %>
    </div>
  <% end %>
</div>

app/views/snippets/new.html.erb
<h1>Create New Code Snippet</h1>

<%= render "form" %>

app/views/snippets/show.html.erb
<h1><%= @s.kind %></h1>
<h3><%= @s.title %></h3>
<pre><code><%= @s.work %></code></pre>

<%= link_to "Edit", edit_snippet_path(@s), class: "btn btn-info btn-sm" %>
<%= link_to "Delete", snippet_path(@s), {method: :delete, class: "btn btn-danger btn-sm", data: {confirm: "Are you sure you want to delete this code snippet?"}}%>